name: myapp
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter  
  flutter_riverpod: ^2.4.0
  riverpodx: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hooks_riverpod: ^2.0.0
  lints: ^3.0.0
